/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.*;
import java.awt.BorderLayout;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Endereco;
import modelo.Veiculo;

/**
 *
 * @author 20162bsi0325
 */
public class Home1 extends javax.swing.JFrame {
    
    ArrayList clientes = null;
    /**
     * Creates new form Home
     */
    public Home1(){
        initComponents();
        setContentPane(Home); 
        Date dataHoraAtual = new Date();
        String data1 = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora1 = new SimpleDateFormat("EEEE, HH:mm zzzz").format(dataHoraAtual);
        data.setText(data1);
        hora.setText(hora1);   
        
                // TODO add your handling code here:
                        //Busca na tabela

    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        Label_Home = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Servico = new javax.swing.JPanel();
        Label_Servico = new javax.swing.JLabel();
        botaoCadastrarServico = new javax.swing.JButton();
        buscarServico = new javax.swing.JTextField();
        botaoBuscarServico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServico = new javax.swing.JTable();
        Veiculos = new javax.swing.JPanel();
        Label_Veiculo = new javax.swing.JLabel();
        pesquisarVeiculos = new javax.swing.JTextField();
        botaoPesquisarVeiculos = new javax.swing.JButton();
        botaoCadastrarVeiculos = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Financeiro = new javax.swing.JPanel();
        Label_Financeiro = new javax.swing.JLabel();
        Scroll_Saida = new javax.swing.JScrollPane();
        tabelaSaidaFinanceiro = new javax.swing.JTable();
        Label_Saida = new javax.swing.JLabel();
        pesquisarSaidaFinanceiro = new javax.swing.JTextField();
        botaopesquisarSaidaFinanceiro = new javax.swing.JButton();
        botaoCadastroSaida = new javax.swing.JButton();
        Scroll_Entrada = new javax.swing.JScrollPane();
        tabelaEntradaFinanceiro = new javax.swing.JTable();
        botaoCadastrarEntradaFinanceiro = new javax.swing.JButton();
        botaoPesquisaEntradaFinanceiro = new javax.swing.JButton();
        pesquisaEntradaFinanceiro = new javax.swing.JTextField();
        Label_Entrada = new javax.swing.JLabel();
        Funcionarios = new javax.swing.JPanel();
        Label_Funcionarios = new javax.swing.JLabel();
        pesquisarFuncionarios = new javax.swing.JTextField();
        botaoPesquisarFuncionarios = new javax.swing.JButton();
        botaoCadastrarFuncionario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        Label_Principal3 = new javax.swing.JLabel();
        pesquisarMotorista = new javax.swing.JTextField();
        botaopesquisarMotorista = new javax.swing.JButton();
        botaoCadastroMotorista = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMotorista = new javax.swing.JTable();
        Clientes = new javax.swing.JPanel();
        Label_Clientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        pesquisarCliente = new javax.swing.JTextField();
        botaoPesquisarCliente = new javax.swing.JButton();
        botaoCadastrarCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        servicosMenu = new javax.swing.JMenu();
        veiculosMenu = new javax.swing.JMenu();
        financeiroMenu = new javax.swing.JMenu();
        funcionariosMenu = new javax.swing.JMenu();
        clientesMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setBackground(new java.awt.Color(255, 255, 255));

        Label_Home.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Home.setText("Inicio");

        data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        data.setText("data");

        hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora.setText("hora");

        jLabel1.setText("Versão 1.1");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(data)
                    .addComponent(jLabel1)
                    .addComponent(hora))
                .addGap(121, 121, 121))
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Label_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Label_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );

        Servico.setBackground(new java.awt.Color(255, 255, 255));

        Label_Servico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Servico.setText("Serviço");

        botaoCadastrarServico.setText("Cadastrar Novo Serviço");
        botaoCadastrarServico.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastrarServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botaoCadastrarServico.setBorderPainted(false);
        botaoCadastrarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarServicoMouseClicked(evt);
            }
        });
        botaoCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarServicoActionPerformed(evt);
            }
        });

        buscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarServicoActionPerformed(evt);
            }
        });

        botaoBuscarServico.setBackground(new java.awt.Color(255, 255, 255));
        botaoBuscarServico.setText("Buscar Serviço");
        botaoBuscarServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoBuscarServico.setBorderPainted(false);
        botaoBuscarServico.setMaximumSize(new java.awt.Dimension(147, 23));
        botaoBuscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarServicoActionPerformed(evt);
            }
        });

        tabelaServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Veiculos", "Origem", "Destino", "Data Inicio", "Data Fim", "Cliente", "Status", "Detalhes"
            }
        ));
        jScrollPane1.setViewportView(tabelaServico);
        if (tabelaServico.getColumnModel().getColumnCount() > 0) {
            tabelaServico.getColumnModel().getColumn(6).setHeaderValue("Cliente");
            tabelaServico.getColumnModel().getColumn(7).setHeaderValue("Status");
            tabelaServico.getColumnModel().getColumn(8).setHeaderValue("Detalhes");
        }

        javax.swing.GroupLayout ServicoLayout = new javax.swing.GroupLayout(Servico);
        Servico.setLayout(ServicoLayout);
        ServicoLayout.setHorizontalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Label_Servico)
                .addGap(18, 18, 18)
                .addComponent(buscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBuscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(botaoCadastrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ServicoLayout.setVerticalGroup(
            ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Servico)
                    .addComponent(buscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        Veiculos.setBackground(new java.awt.Color(255, 255, 255));

        Label_Veiculo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Veiculo.setText("Veiculos");

        pesquisarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarVeiculosActionPerformed(evt);
            }
        });

        botaoPesquisarVeiculos.setText("Pesquisar");

        botaoCadastrarVeiculos.setText("Cadastrar");
        botaoCadastrarVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarVeiculosMouseClicked(evt);
            }
        });
        botaoCadastrarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarVeiculosActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabela);

        javax.swing.GroupLayout VeiculosLayout = new javax.swing.GroupLayout(Veiculos);
        Veiculos.setLayout(VeiculosLayout);
        VeiculosLayout.setHorizontalGroup(
            VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeiculosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Label_Veiculo)
                .addGap(101, 101, 101)
                .addComponent(pesquisarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisarVeiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(botaoCadastrarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(VeiculosLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VeiculosLayout.setVerticalGroup(
            VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VeiculosLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(VeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Veiculo)
                    .addComponent(pesquisarVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarVeiculos)
                    .addComponent(botaoCadastrarVeiculos))
                .addGap(107, 107, 107)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        Financeiro.setBackground(new java.awt.Color(255, 255, 255));

        Label_Financeiro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Financeiro.setText("Financeiro");

        tabelaSaidaFinanceiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "CNH", "Categoria", "Validade", "Detalhes"
            }
        ));
        Scroll_Saida.setViewportView(tabelaSaidaFinanceiro);

        Label_Saida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Saida.setText("Tabela de Saida");

        pesquisarSaidaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarSaidaFinanceiroActionPerformed(evt);
            }
        });

        botaopesquisarSaidaFinanceiro.setText("Pesquisar");

        botaoCadastroSaida.setText("Cadastrar");
        botaoCadastroSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroSaidaMouseClicked(evt);
            }
        });
        botaoCadastroSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroSaidaActionPerformed(evt);
            }
        });

        tabelaEntradaFinanceiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "Detalhes"
            }
        ));
        Scroll_Entrada.setViewportView(tabelaEntradaFinanceiro);

        botaoCadastrarEntradaFinanceiro.setText("Cadastrar");
        botaoCadastrarEntradaFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarEntradaFinanceiroMouseClicked(evt);
            }
        });
        botaoCadastrarEntradaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEntradaFinanceiroActionPerformed(evt);
            }
        });

        botaoPesquisaEntradaFinanceiro.setText("Pesquisar");
        botaoPesquisaEntradaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaEntradaFinanceiroActionPerformed(evt);
            }
        });

        pesquisaEntradaFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaEntradaFinanceiroActionPerformed(evt);
            }
        });

        Label_Entrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Entrada.setText("Tabela de Entrada");

        javax.swing.GroupLayout FinanceiroLayout = new javax.swing.GroupLayout(Financeiro);
        Financeiro.setLayout(FinanceiroLayout);
        FinanceiroLayout.setHorizontalGroup(
            FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinanceiroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Entrada)
                    .addComponent(Label_Financeiro))
                .addGap(74, 74, 74)
                .addComponent(pesquisaEntradaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisaEntradaFinanceiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastrarEntradaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinanceiroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Label_Saida)
                .addGap(99, 99, 99)
                .addComponent(pesquisarSaidaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaopesquisarSaidaFinanceiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastroSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(FinanceiroLayout.createSequentialGroup()
                .addGroup(FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinanceiroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Scroll_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinanceiroLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Scroll_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        FinanceiroLayout.setVerticalGroup(
            FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinanceiroLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Financeiro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisaEntradaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoPesquisaEntradaFinanceiro)
                        .addComponent(botaoCadastrarEntradaFinanceiro)))
                .addGap(18, 18, 18)
                .addComponent(Label_Entrada)
                .addGap(14, 14, 14)
                .addComponent(Scroll_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(FinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarSaidaFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisarSaidaFinanceiro)
                    .addComponent(botaoCadastroSaida)
                    .addComponent(Label_Saida))
                .addGap(38, 38, 38)
                .addComponent(Scroll_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        Funcionarios.setBackground(new java.awt.Color(255, 255, 255));

        Label_Funcionarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Funcionarios.setText("Funcionarios");

        pesquisarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarFuncionariosActionPerformed(evt);
            }
        });

        botaoPesquisarFuncionarios.setText("Pesquisar");

        botaoCadastrarFuncionario.setText("Cadastrar");
        botaoCadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarFuncionarioMouseClicked(evt);
            }
        });
        botaoCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarFuncionarioActionPerformed(evt);
            }
        });

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "Detalhes"
            }
        ));
        jScrollPane3.setViewportView(tabelaFuncionarios);

        Label_Principal3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Principal3.setText("Motorista");

        pesquisarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarMotoristaActionPerformed(evt);
            }
        });

        botaopesquisarMotorista.setText("Pesquisar");

        botaoCadastroMotorista.setText("Cadastrar");
        botaoCadastroMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroMotoristaMouseClicked(evt);
            }
        });
        botaoCadastroMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroMotoristaActionPerformed(evt);
            }
        });

        tabelaMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "Endereço", "CPF", "Email", "CNH", "Categoria", "Validade", "Detalhes"
            }
        ));
        jScrollPane4.setViewportView(tabelaMotorista);

        javax.swing.GroupLayout FuncionariosLayout = new javax.swing.GroupLayout(Funcionarios);
        Funcionarios.setLayout(FuncionariosLayout);
        FuncionariosLayout.setHorizontalGroup(
            FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionariosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Label_Funcionarios)
                .addGap(74, 74, 74)
                .addComponent(pesquisarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisarFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(botaoCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(FuncionariosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Label_Principal3)
                .addGap(99, 99, 99)
                .addComponent(pesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaopesquisarMotorista)
                .addGap(53, 53, 53)
                .addComponent(botaoCadastroMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(FuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        FuncionariosLayout.setVerticalGroup(
            FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesquisarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoPesquisarFuncionarios)
                        .addComponent(botaoCadastrarFuncionario)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(FuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisarMotorista)
                    .addComponent(botaoCadastroMotorista)
                    .addComponent(Label_Principal3))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        Clientes.setBackground(new java.awt.Color(255, 255, 255));

        Label_Clientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Clientes.setText("Cliente");

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "n°", "Nome", "CPF", "CNPJ", "Contato", "Endereço"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaClientes);

        pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClienteActionPerformed(evt);
            }
        });

        botaoPesquisarCliente.setText("Pesquisar");

        botaoCadastrarCliente.setText("Cadastrar");
        botaoCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarClienteMouseClicked(evt);
            }
        });
        botaoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Label_Clientes)
                .addGap(101, 101, 101)
                .addComponent(pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(botaoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(ClientesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientesLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Clientes)
                    .addComponent(pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarCliente)
                    .addComponent(botaoCadastrarCliente))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        homeMenu.setText("Home");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        servicosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/support.png"))); // NOI18N
        servicosMenu.setText("Serviços");
        servicosMenu.setIconTextGap(2);
        servicosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(servicosMenu);

        veiculosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/truck.png"))); // NOI18N
        veiculosMenu.setText("Veiculos");
        veiculosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veiculosMenuMouseClicked(evt);
            }
        });
        veiculosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculosMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(veiculosMenu);

        financeiroMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/debt.png"))); // NOI18N
        financeiroMenu.setText("Financeiro");
        financeiroMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financeiroMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(financeiroMenu);

        funcionariosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/employee.png"))); // NOI18N
        funcionariosMenu.setText("Funcionarios");
        funcionariosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionariosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(funcionariosMenu);

        clientesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/avatar.png"))); // NOI18N
        clientesMenu.setText("Clientes");
        clientesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(clientesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Veiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Financeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Veiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Financeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Funcionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servicosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicosMenuMouseClicked
        setContentPane(Servico); 
        // TODO add your handling code here:
    }//GEN-LAST:event_servicosMenuMouseClicked

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        setContentPane(Home);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void botaoCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarServicoActionPerformed

    private void buscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarServicoActionPerformed

    private void pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarClienteActionPerformed

    private void botaoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarClienteActionPerformed

    private void pesquisarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarFuncionariosActionPerformed

    private void botaoCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarFuncionarioActionPerformed

    private void pesquisarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarMotoristaActionPerformed

    private void botaoCadastroMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroMotoristaActionPerformed

    private void pesquisarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarVeiculosActionPerformed

    private void botaoCadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarVeiculosActionPerformed
                  // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarVeiculosActionPerformed

    private void pesquisarSaidaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarSaidaFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarSaidaFinanceiroActionPerformed

    private void botaoCadastroSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroSaidaActionPerformed

    private void botaoCadastrarEntradaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEntradaFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarEntradaFinanceiroActionPerformed

    private void pesquisaEntradaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaEntradaFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaEntradaFinanceiroActionPerformed

    private void botaoPesquisaEntradaFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaEntradaFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisaEntradaFinanceiroActionPerformed

    private void veiculosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculosMenuMouseClicked
        // TODO add your handling code here:
        
        VeiculoBD veiculoBD = new VeiculoBD();
        ArrayList veiculos = null;
        try {
            veiculos = veiculoBD.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Veiculos.setLayout(new BorderLayout());
        TABELA aux = new TABELA();
        aux.dadostabelV(veiculos,tabela);   
        setContentPane(Veiculos);
        
    }//GEN-LAST:event_veiculosMenuMouseClicked

    private void financeiroMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financeiroMenuMouseClicked
        // TODO add your handling code here:
        setContentPane(Financeiro);         
    }//GEN-LAST:event_financeiroMenuMouseClicked

    private void funcionariosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionariosMenuMouseClicked
        // TODO add your handling code here:
        setContentPane(Funcionarios); 
    }//GEN-LAST:event_funcionariosMenuMouseClicked

    private void clientesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMenuMouseClicked
        // TODO add your handling code here:
        ClienteBD clientes_conn = new ClienteBD();
        
        
        try {
            clientes = clientes_conn.select("");
        } catch (SQLException ex) {
            Logger.getLogger(Home1.class.getName()).log(Level.SEVERE, null, ex);
        }

        Veiculos.setLayout(new BorderLayout());
        TABELA aux = new TABELA();
        aux.dadostabelC(clientes,tabelaClientes);   
        
        setContentPane(Clientes); 
    }//GEN-LAST:event_clientesMenuMouseClicked

    private void botaoCadastrarServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarServicoMouseClicked
        // TODO add your handling code here:
        CadastroServico cadastro_Servico = new CadastroServico();
        cadastro_Servico.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarServicoMouseClicked

    private void botaoCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarClienteMouseClicked
        // TODO add your handling code here:
         CadastroCliente Cadastro_Cliente = new CadastroCliente();
        Cadastro_Cliente.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarClienteMouseClicked

    private void botaoCadastrarVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarVeiculosMouseClicked
        // TODO add your handling code here:
        CadastroVeiculo Cadastro_Veiculo = new CadastroVeiculo();
        Cadastro_Veiculo.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarVeiculosMouseClicked

    private void botaoCadastrarEntradaFinanceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarEntradaFinanceiroMouseClicked
         CadastroFinanceiroEntrada Cadastro_Entrada = new CadastroFinanceiroEntrada();
        Cadastro_Entrada.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarEntradaFinanceiroMouseClicked

    private void botaoCadastroSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroSaidaMouseClicked
        CadastroFinanceiroSaida Cadastro_Saida = new CadastroFinanceiroSaida();
        Cadastro_Saida.setVisible(true);
        // TODO add your handling code here:
            
    }//GEN-LAST:event_botaoCadastroSaidaMouseClicked

    private void botaoCadastrarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarFuncionarioMouseClicked
        // TODO add your handling code here:
        CadastroFuncionario Cadastro_Funcionario = new CadastroFuncionario();
        Cadastro_Funcionario.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarFuncionarioMouseClicked

    private void botaoBuscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBuscarServicoActionPerformed

    private void botaoCadastroMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroMotoristaMouseClicked
        CadastroMotorista Cadatro_Motorista = new CadastroMotorista();
        Cadatro_Motorista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroMotoristaMouseClicked

    private void veiculosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculosMenuActionPerformed

    }//GEN-LAST:event_veiculosMenuActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
 
    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // TODO add your handling code here:
        int linha = tabelaClientes.getSelectedRow();
        this.clientes.get(linha);        
    }//GEN-LAST:event_tabelaClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Financeiro;
    private javax.swing.JPanel Funcionarios;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Label_Clientes;
    private javax.swing.JLabel Label_Entrada;
    private javax.swing.JLabel Label_Financeiro;
    private javax.swing.JLabel Label_Funcionarios;
    private javax.swing.JLabel Label_Home;
    private javax.swing.JLabel Label_Principal3;
    private javax.swing.JLabel Label_Saida;
    private javax.swing.JLabel Label_Servico;
    private javax.swing.JLabel Label_Veiculo;
    private javax.swing.JScrollPane Scroll_Entrada;
    private javax.swing.JScrollPane Scroll_Saida;
    private javax.swing.JPanel Servico;
    private javax.swing.JPanel Veiculos;
    private javax.swing.JButton botaoBuscarServico;
    private javax.swing.JButton botaoCadastrarCliente;
    private javax.swing.JButton botaoCadastrarEntradaFinanceiro;
    private javax.swing.JButton botaoCadastrarFuncionario;
    private javax.swing.JButton botaoCadastrarServico;
    private javax.swing.JButton botaoCadastrarVeiculos;
    private javax.swing.JButton botaoCadastroMotorista;
    private javax.swing.JButton botaoCadastroSaida;
    private javax.swing.JButton botaoPesquisaEntradaFinanceiro;
    private javax.swing.JButton botaoPesquisarCliente;
    private javax.swing.JButton botaoPesquisarFuncionarios;
    private javax.swing.JButton botaoPesquisarVeiculos;
    private javax.swing.JButton botaopesquisarMotorista;
    private javax.swing.JButton botaopesquisarSaidaFinanceiro;
    private javax.swing.JTextField buscarServico;
    private javax.swing.JMenu clientesMenu;
    private javax.swing.JLabel data;
    private javax.swing.JMenu financeiroMenu;
    private javax.swing.JMenu funcionariosMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField pesquisaEntradaFinanceiro;
    private javax.swing.JTextField pesquisarCliente;
    private javax.swing.JTextField pesquisarFuncionarios;
    private javax.swing.JTextField pesquisarMotorista;
    private javax.swing.JTextField pesquisarSaidaFinanceiro;
    private javax.swing.JTextField pesquisarVeiculos;
    private javax.swing.JMenu servicosMenu;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaEntradaFinanceiro;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTable tabelaMotorista;
    private javax.swing.JTable tabelaSaidaFinanceiro;
    private javax.swing.JTable tabelaServico;
    private javax.swing.JMenu veiculosMenu;
    // End of variables declaration//GEN-END:variables

}
